// lib/data/recipes-index.ts
// Lightweight recipe index for initial page loads
// Full recipe bodies are lazy-loaded on demand

import type { Recipe } from '../types';

export interface RecipeIndexEntry {
  id: string;
  name: string;
  shortName?: string;
  category: string;
  tags?: string[];
  baseScore?: number; // Precomputed base compatibility score if available
  healthConcerns?: string[];
  ageGroup?: string[];
  imageUrl?: string;
  prepTime?: string;
  servings?: number;
}

/**
 * Generate lightweight index from full recipes
 * This is a build-time helper - actual index should be generated by script
 */
export function generateRecipeIndex(recipes: Recipe[]): RecipeIndexEntry[] {
  return recipes.map(recipe => ({
    id: recipe.id,
    name: recipe.name,
    shortName: recipe.shortName,
    category: recipe.category,
    tags: recipe.tags,
    healthConcerns: recipe.healthConcerns,
    ageGroup: recipe.ageGroup,
    imageUrl: recipe.imageUrl,
    prepTime: recipe.prepTime,
    servings: recipe.servings,
  }));
}

/**
 * Lazy load full recipe by ID
 */
export async function loadRecipeById(id: string): Promise<Recipe | null> {
  try {
    const recipesModule = await import('./recipes-complete');
    const recipes = recipesModule.recipes;
    return recipes.find(r => r.id === id) || null;
  } catch (error) {
    console.error('Failed to load recipe:', error);
    return null;
  }
}

/**
 * Lazy load multiple recipes by IDs
 */
export async function loadRecipesByIds(ids: string[]): Promise<Recipe[]> {
  try {
    const recipesModule = await import('./recipes-complete');
    const recipes = recipesModule.recipes;
    return recipes.filter(r => ids.includes(r.id));
  } catch (error) {
    console.error('Failed to load recipes:', error);
    return [];
  }
}

/**
 * Lazy load all recipes (for when full data is needed)
 */
export async function loadAllRecipes(): Promise<Recipe[]> {
  try {
    const recipesModule = await import('./recipes-complete');
    return recipesModule.recipes;
  } catch (error) {
    console.error('Failed to load all recipes:', error);
    return [];
  }
}

