// lib/data/recipes-index.ts
// Lightweight recipe index for initial page loads
// Full recipe bodies are lazy-loaded on demand

import type { Recipe } from '../types';

export interface RecipeIndexEntry {
  id: string;
  name: string;
  shortName?: string;
  category: string;
  tags?: string[];
  baseScore?: number; // Precomputed base compatibility score if available
  healthConcerns?: string[];
  ageGroup?: string[];
  imageUrl?: string;
  prepTime?: string;
  servings?: number;
}

/**
 * Generate lightweight index from full recipes
 * This is a build-time helper - actual index should be generated by script
 */
export function generateRecipeIndex(recipes: Recipe[]): RecipeIndexEntry[] {
  return recipes.map(recipe => ({
    id: recipe.id,
    name: recipe.name,
    shortName: recipe.shortName,
    category: recipe.category,
    tags: recipe.tags,
    healthConcerns: recipe.healthConcerns,
    ageGroup: recipe.ageGroup,
    imageUrl: recipe.imageUrl,
    prepTime: recipe.prepTime,
    servings: recipe.servings,
  }));
}

/**
 * Load a single recipe by ID
 * Recipes are now generated dynamically - returns null
 */
export async function loadRecipeById(id: string): Promise<Recipe | null> {
  return null;
}

/**
 * Load multiple recipes by IDs
 * Recipes are now generated dynamically - returns empty array
 */
export async function loadRecipesByIds(ids: string[]): Promise<Recipe[]> {
  return [];
}

/**
 * Load all recipes
 * Recipes are now generated dynamically - returns empty array
 */
export async function loadAllRecipes(): Promise<Recipe[]> {
  return [];
}
