// scripts/check-link-health.ts
// Optional: Check if ASINs are still valid (HTTP HEAD requests)
// Can be run periodically to detect broken/discontinued products

import * as fs from 'fs';
import * as path from 'path';
import { extractASIN } from '../lib/utils/affiliateLinks';

const VETTED_PRODUCTS_FILE = path.join(__dirname, '../lib/data/vetted-products.ts');

interface HealthResult {
  ingredient: string;
  asin: string;
  link: string;
  status: 'unknown' | 'valid' | 'broken' | 'error';
  error?: string;
}

const results: HealthResult[] = [];

// Check if ASIN link is still valid (optional HTTP check)
// Note: This requires making HTTP requests, so it's optional and can be slow
async function checkASINHealth(asin: string, link: string): Promise<'valid' | 'broken' | 'error'> {
  // This is a placeholder - actual implementation would make HTTP HEAD request
  // For now, we'll just validate the ASIN format and URL structure
  // Full implementation would require:
  // - HTTP client (axios, node-fetch, etc.)
  // - Rate limiting to avoid overwhelming Amazon
  // - Error handling for network issues
  
  try {
    // Basic validation
    if (!asin || asin.length !== 10) {
      return 'error';
    }
    
    if (!link || !link.includes('amazon.com')) {
      return 'error';
    }
    
    // For now, assume valid if format is correct
    // To implement actual HTTP checking, uncomment and configure:
    /*
    const response = await fetch(link, { method: 'HEAD', redirect: 'follow' });
    if (response.ok) {
      return 'valid';
    } else if (response.status === 404) {
      return 'broken';
    } else {
      return 'error';
    }
    */
    
    return 'unknown';
  } catch (error) {
    return 'error';
  }
}

// Extract all ASINs from vetted products
function extractAllASINs() {
  const content = fs.readFileSync(VETTED_PRODUCTS_FILE, 'utf-8');
  const lines = content.split('\n');
  
  let currentIngredient: string | null = null;
  let currentLink: string | null = null;
  let inProductBlock = false;
  let braceDepth = 0;
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    const ingredientMatch = line.match(/^\s*'([^']+)':\s*\{/);
    if (ingredientMatch) {
      currentIngredient = ingredientMatch[1];
      inProductBlock = true;
      braceDepth = 1;
      currentLink = null;
      continue;
    }
    
    if (inProductBlock) {
      braceDepth += (line.match(/\{/g) || []).length;
      braceDepth -= (line.match(/\}/g) || []).length;
      
      const asinMatch = line.match(/asinLink:\s*'([^']+)'/);
      if (asinMatch) {
        currentLink = asinMatch[1];
      }
      
      if (braceDepth === 0) {
        if (currentIngredient && currentLink) {
          const asin = extractASIN(currentLink);
          if (asin) {
            results.push({
              ingredient: currentIngredient,
              asin,
              link: currentLink,
              status: 'unknown',
            });
          }
        }
        
        currentIngredient = null;
        currentLink = null;
        inProductBlock = false;
      }
    }
  }
}

// Generate health report
function generateHealthReport() {
  const reportPath = path.join(__dirname, '../LINK_HEALTH_REPORT.md');
  
  const valid = results.filter(r => r.status === 'valid').length;
  const broken = results.filter(r => r.status === 'broken').length;
  const errors = results.filter(r => r.status === 'error').length;
  const unknown = results.filter(r => r.status === 'unknown').length;
  
  const report = `# Link Health Check Report
Generated: ${new Date().toISOString()}

## Summary
- Total links checked: ${results.length}
- Valid: ${valid}
- Broken: ${broken}
- Errors: ${errors}
- Unknown (format check only): ${unknown}

## Note
This report currently only validates ASIN format and URL structure.
To enable actual HTTP health checking, implement HTTP requests in check-link-health.ts.

## Results

${results.map(r => `
### ${r.ingredient}
- ASIN: ${r.asin}
- Status: ${r.status}
- Link: ${r.link}
${r.error ? `- Error: ${r.error}` : ''}
`).join('\n')}

## Recommendations

1. **Review broken links**: Replace discontinued products
2. **Monitor regularly**: Run this check monthly
3. **Implement HTTP checking**: Enable actual link validation (see script comments)

---

*Report generated by check-link-health.ts*
`;

  fs.writeFileSync(reportPath, report);
  console.log(`\n💾 Report saved to: ${reportPath}`);
}

// Main execution
async function main() {
  console.log('🏥 Link Health Check\n');
  console.log('='.repeat(60));
  console.log('Note: This script currently validates format only.');
  console.log('To enable HTTP checking, see script comments.\n');
  
  extractAllASINs();
  
  // Optionally check each ASIN (currently skipped for performance)
  // Uncomment to enable actual HTTP checking:
  /*
  console.log(`Checking ${results.length} links...`);
  for (const result of results) {
    result.status = await checkASINHealth(result.asin, result.link);
    process.stdout.write('.');
  }
  console.log('\n');
  */
  
  generateHealthReport();
  
  console.log('='.repeat(60));
  console.log('📊 HEALTH CHECK SUMMARY\n');
  console.log(`Total links: ${results.length}`);
  console.log(`Status: Format validation only (HTTP checking disabled)`);
  console.log(`\n✅ Health check complete!\n`);
}

main().catch(error => {
  console.error('❌ Error running health check:', error);
  process.exit(1);
});

